### ISSUE TITLE
建议在 axdtb 和 axtype 的 Cargo.toml 依赖中使用 https 而不是 ssh 的 git 地址

### ISSUE THREAD

**Issue by zjp-CN** [shilei-massclouds/axdtb#1]
https://github.com/shilei-massclouds/axdtb/blob/b14c39d7beec2e8b68a890e95a38dbb45045061a/axdtb/Cargo.toml#L9

```diff
# axdtb/Cargo.toml
-axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype.git" }
+axtype = { git = "https://github.com/shilei-massclouds/axtype.git" }
```

https://github.com/shilei-massclouds/axtype/blob/e48d1d9fa24f887f3863a01621251116bf560ae3/axtype/Cargo.toml#L9

```diff
# axtype/Cargo.toml
-axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
+axconfig = { git = "https://github.com/shilei-massclouds/axconfig.git" }
```

使用 ssh 协议的地址会无法拉取这些依赖：

```console
    Updating git repository `ssh://git@github.com/shilei-massclouds/axtype.git`
info: installing component 'rust-std'
error: failed to get `axtype` as a dependency of package `axdtb v0.1.0 (/ci/axdtb/axdtb)`

Caused by:
  failed to load source for dependency `axtype`

Caused by:
  Unable to update ssh://git@github.com/shilei-massclouds/axtype.git

Caused by:
  failed to clone into: /root/.cargo/git/db/axtype-5d4f3cfbafdc70ef

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication methods succeeded
```

**Comment by shilei-massclouds** [comment]
ssh和https各有优劣。ssh方式需要配置github证书认证吧。
根据建议，我准备尝试一下ssh+https的url，看看效果上能否达到同时支持的目的。

**Comment by zjp-CN** [comment]
嗯... 我试了一下，在本地配置了 ssh 的情况下，的确能成功拉取这些依赖。

但 [os-checker](https://github.com/os-checker/os-checker) 主要通过 CI 编译和检查代码库，要使用 ssh ，需要以下一些步骤

* 添加公钥到 os-checker 组织下的一些仓库中的 Deploy keys
* 存储密钥到 os-checker 组织，并在 Github Action 中读取和设置
  * 由于检查实际最终在 docker 内运行，还要把密钥文件复制进容器内（密钥不能随容器分发，所以要多一些 CI 和 docker 步骤进行设置...）

---

有很强的理由在 **公开的依赖上** 坚持 ssh 协议而不是 https 协议吗？

**Comment by zjp-CN** [comment]
我已经[在 os-checker 的 CI 设置了 SSH 认证](https://github.com/os-checker/os-checker/issues/67)，所以关闭这个。
